let city = [
    "Les Irois",
    "Anse-d'Hainault",
    "Aquin",
    "Cavaellon",
    "Fond-des-Blancs",
    "Saint-Louis-du-Sud",
    "Arcahaie",
    "Cabaret",
    "Bainet",
    "Côtes-de-Fer",
    "Baradères",
    "Grand-Boucan",
    "Anse-à-Pitres",
    "Belle-Anse",
    "Grand-Gosier",
    "Thiotte",
    "Borgne",
    "Port-Margot",
    "Cap-Haïtien",
    "Limonade",
    "Quartier-Morin",
    "Cerca-la-Source",
    "Thomassique",
    "Chardonnières",
    "Les Anglais",
    "Beaumont",
    "Corail",
    "Pestel",
    "Côteaux",
    "Port-à-Piment",
    "Roche-à-Bateaux",
    "Cornillon",
    "Croix-des-Bouquets",
    "Fonds-Verrettes",
    "Ganthier",
    "Thomazeau",
    "Desdunes",
    "Dessalines",
    "Grande-Saline",
    "Petite Rivière de l'Artibonite",
    "Saint-Michel-de-l'Atalaye",
    "Ferrier",
    "Fort-Liberté",
    "Perches",
    "Ennery",
    "Gonaïves",
    "L'Estère",
    "Anse-à-Galets",
    "Bahon",
    "Grande-Rivière-du-Nord",
    "Anse-Rouge",
    "Gros-Morne",
    "Terre-Neuve",
    "Cerca-Carvajal",
    "Hinche",
    "Maïssade",
    "Thomonde",
    "Cayes-Jacmel",
    "Jacmel",
    "La Vallée-de-Jacmel",
    "Marigot",
    "Abricots",
    "Bonbon",
    "Chambellan",
    "Jérémie",
    "Moron",
    "Roseaux",
    "Pointe-à-Raquette",
    "Belladère",
    "Lascahobas",
    "Savanette",
    "Grand-Goâve",
    "Léogâne",
    "Petit-Goâve",
    "Camp-Perrin",
    "Chantal",
    "Île-à-Vache",
    "Les Cayes",
    "Maniche",
    "Torbeck",
    "Bas-Limbé",
    "Limbé",
    "Marmelade",
    "Fonds-des-Nègres",
    "Miragoâne",
    "Paillant",
    "Petite-Rivière-de-Nippes",
    "Boucan-Carré",
    "Mirebalais",
    "Saut-d'Eau",
    "Baie-de-Henne",
    "Bombardopolis",
    "Jean-Rabel",
    "Môle-Saint-Nicolas",
    "Capotille",
    "Mont-Organisé",
    "Ouanaminthe",
    "Pilate",
    "Plaisance",
    "Carrefour",
    "Cité Soleil",
    "Delmas",
    "Gressier",
    "Kenscoff",
    "Pétion-Ville",
    "Port-au-Prince",
    "Tabarre",
    "Bassin-Bleu",
    "Chansolme",
    "Île de la Tortue",
    "Port-de-Paix",
    "Arniquet",
    "Port-Salut",
    "Saint-Jean-du-Sud",
    "Anse-à-Foleur",
    "Saint-Louis-du-Nord",
    "La Chapelle",
    "Saint-Marc",
    "Verrettes",
    "Dondon",
    "La Victoire",
    "Pignon",
    "Ranquitte",
    "Saint-Raphaël",
    "Caracol",
    "Sainte-Suzanne",
    "Terrier-Rouge",
    "Trou-du-Nord",
    "Carice",
    "Mombin-Crochu",
    "Vallières",
  ];
  
  
  export default city